# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='otp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\totp.proto\";\n\x03Otp\x12\x0b\n\x03otp\x18\x01 \x02(\r\x12\x14\n\x0cmobilenumber\x18\x02 \x02(\x04\x12\x11\n\ttimestamp\x18\x03 \x02(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OTP = _descriptor.Descriptor(
  name='Otp',
  full_name='Otp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='otp', full_name='Otp.otp', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobilenumber', full_name='Otp.mobilenumber', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Otp.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['Otp'] = _OTP

Otp = _reflection.GeneratedProtocolMessageType('Otp', (_message.Message,), dict(
  DESCRIPTOR = _OTP,
  __module__ = 'otp_pb2'
  # @@protoc_insertion_point(class_scope:Otp)
  ))
_sym_db.RegisterMessage(Otp)


# @@protoc_insertion_point(module_scope)
