# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agpayload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
sys.path.insert(0, "../")

import proto.enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agpayload.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x61gpayload.proto\x1a\x0b\x65nums.proto\"\xb8\x01\n\x0fRegister_farmer\x12\x13\n\x0b\x61\x61\x64har_card\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x11\n\tfull_name\x18\x03 \x02(\t\x12\x15\n\x05State\x18\x04 \x02(\x0e\x32\x06.state\x12\x0f\n\x07pincode\x18\x05 \x02(\r\x12\x14\n\x0cmobilenumber\x18\x06 \x02(\x04\x12\x10\n\x08\x64istrict\x18\x07 \x02(\t\x12\r\n\x05photo\x18\x08 \x01(\x0c\x12\x0b\n\x03otp\x18\t \x02(\r\"\xb7\x01\n\x0eRegister_buyer\x12\x13\n\x0b\x61\x61\x64har_card\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x11\n\tfull_name\x18\x03 \x02(\t\x12\x15\n\x05State\x18\x04 \x02(\x0e\x32\x06.state\x12\x0f\n\x07pincode\x18\x05 \x02(\r\x12\x14\n\x0cmobilenumber\x18\x06 \x02(\x04\x12\x10\n\x08\x64istrict\x18\x07 \x02(\t\x12\r\n\x05photo\x18\x08 \x01(\x0c\x12\x0b\n\x03otp\x18\t \x02(\r\"\xd6\x01\n\x14Register_transporter\x12\x13\n\x0b\x61\x61\x64har_card\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x11\n\tfull_name\x18\x03 \x02(\t\x12\x15\n\x05State\x18\x04 \x02(\x0e\x32\x06.state\x12\x0f\n\x07pincode\x18\x05 \x02(\r\x12\x14\n\x0cmobilenumber\x18\x06 \x02(\x04\x12\x10\n\x08\x64istrict\x18\x07 \x02(\t\x12\x17\n\x0f\x64riving_license\x18\x08 \x02(\t\x12\r\n\x05photo\x18\t \x01(\x0c\x12\x0b\n\x03otp\x18\n \x02(\r\"G\n\x0fOtp_transaction\x12\x14\n\x0cmobilenumber\x18\x01 \x02(\x04\x12\x0b\n\x03otp\x18\x02 \x02(\r\x12\x11\n\ttimestamp\x18\x03 \x02(\r\"\xb6\x01\n\x0bRealpayload\x12\x17\n\x06\x41\x63tion\x18\x01 \x02(\x0e\x32\x07.action\x12!\n\x07reg_far\x18\x02 \x01(\x0b\x32\x10.Register_farmer\x12 \n\x07reg_buy\x18\x03 \x01(\x0b\x32\x0f.Register_buyer\x12&\n\x07reg_tra\x18\x04 \x01(\x0b\x32\x15.Register_transporter\x12!\n\x07otp_tra\x18\x05 \x01(\x0b\x32\x10.Otp_transaction*`\n\x06\x61\x63tion\x12\x13\n\x0fregister_farmer\x10\x00\x12\x12\n\x0eregister_buyer\x10\x01\x12\x18\n\x14register_transporter\x10\x02\x12\x13\n\x0fotp_transaction\x10\x03')
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTION = _descriptor.EnumDescriptor(
  name='action',
  full_name='action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='register_farmer', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='register_buyer', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='register_transporter', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='otp_transaction', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=880,
  serialized_end=976,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
register_farmer = 0
register_buyer = 1
register_transporter = 2
otp_transaction = 3



_REGISTER_FARMER = _descriptor.Descriptor(
  name='Register_farmer',
  full_name='Register_farmer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aadhar_card', full_name='Register_farmer.aadhar_card', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Register_farmer.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='Register_farmer.full_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='State', full_name='Register_farmer.State', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pincode', full_name='Register_farmer.pincode', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobilenumber', full_name='Register_farmer.mobilenumber', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='district', full_name='Register_farmer.district', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photo', full_name='Register_farmer.photo', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otp', full_name='Register_farmer.otp', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=217,
)


_REGISTER_BUYER = _descriptor.Descriptor(
  name='Register_buyer',
  full_name='Register_buyer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aadhar_card', full_name='Register_buyer.aadhar_card', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Register_buyer.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='Register_buyer.full_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='State', full_name='Register_buyer.State', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pincode', full_name='Register_buyer.pincode', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobilenumber', full_name='Register_buyer.mobilenumber', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='district', full_name='Register_buyer.district', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photo', full_name='Register_buyer.photo', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otp', full_name='Register_buyer.otp', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=403,
)


_REGISTER_TRANSPORTER = _descriptor.Descriptor(
  name='Register_transporter',
  full_name='Register_transporter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aadhar_card', full_name='Register_transporter.aadhar_card', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Register_transporter.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='Register_transporter.full_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='State', full_name='Register_transporter.State', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pincode', full_name='Register_transporter.pincode', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobilenumber', full_name='Register_transporter.mobilenumber', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='district', full_name='Register_transporter.district', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='driving_license', full_name='Register_transporter.driving_license', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photo', full_name='Register_transporter.photo', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otp', full_name='Register_transporter.otp', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=620,
)


_OTP_TRANSACTION = _descriptor.Descriptor(
  name='Otp_transaction',
  full_name='Otp_transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobilenumber', full_name='Otp_transaction.mobilenumber', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otp', full_name='Otp_transaction.otp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Otp_transaction.timestamp', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=693,
)


_REALPAYLOAD = _descriptor.Descriptor(
  name='Realpayload',
  full_name='Realpayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Action', full_name='Realpayload.Action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reg_far', full_name='Realpayload.reg_far', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reg_buy', full_name='Realpayload.reg_buy', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reg_tra', full_name='Realpayload.reg_tra', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otp_tra', full_name='Realpayload.otp_tra', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=696,
  serialized_end=878,
)

_REGISTER_FARMER.fields_by_name['State'].enum_type = enums__pb2._STATE
_REGISTER_BUYER.fields_by_name['State'].enum_type = enums__pb2._STATE
_REGISTER_TRANSPORTER.fields_by_name['State'].enum_type = enums__pb2._STATE
_REALPAYLOAD.fields_by_name['Action'].enum_type = _ACTION
_REALPAYLOAD.fields_by_name['reg_far'].message_type = _REGISTER_FARMER
_REALPAYLOAD.fields_by_name['reg_buy'].message_type = _REGISTER_BUYER
_REALPAYLOAD.fields_by_name['reg_tra'].message_type = _REGISTER_TRANSPORTER
_REALPAYLOAD.fields_by_name['otp_tra'].message_type = _OTP_TRANSACTION
DESCRIPTOR.message_types_by_name['Register_farmer'] = _REGISTER_FARMER
DESCRIPTOR.message_types_by_name['Register_buyer'] = _REGISTER_BUYER
DESCRIPTOR.message_types_by_name['Register_transporter'] = _REGISTER_TRANSPORTER
DESCRIPTOR.message_types_by_name['Otp_transaction'] = _OTP_TRANSACTION
DESCRIPTOR.message_types_by_name['Realpayload'] = _REALPAYLOAD
DESCRIPTOR.enum_types_by_name['action'] = _ACTION

Register_farmer = _reflection.GeneratedProtocolMessageType('Register_farmer', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_FARMER,
  __module__ = 'agpayload_pb2'
  # @@protoc_insertion_point(class_scope:Register_farmer)
  ))
_sym_db.RegisterMessage(Register_farmer)

Register_buyer = _reflection.GeneratedProtocolMessageType('Register_buyer', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_BUYER,
  __module__ = 'agpayload_pb2'
  # @@protoc_insertion_point(class_scope:Register_buyer)
  ))
_sym_db.RegisterMessage(Register_buyer)

Register_transporter = _reflection.GeneratedProtocolMessageType('Register_transporter', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_TRANSPORTER,
  __module__ = 'agpayload_pb2'
  # @@protoc_insertion_point(class_scope:Register_transporter)
  ))
_sym_db.RegisterMessage(Register_transporter)

Otp_transaction = _reflection.GeneratedProtocolMessageType('Otp_transaction', (_message.Message,), dict(
  DESCRIPTOR = _OTP_TRANSACTION,
  __module__ = 'agpayload_pb2'
  # @@protoc_insertion_point(class_scope:Otp_transaction)
  ))
_sym_db.RegisterMessage(Otp_transaction)

Realpayload = _reflection.GeneratedProtocolMessageType('Realpayload', (_message.Message,), dict(
  DESCRIPTOR = _REALPAYLOAD,
  __module__ = 'agpayload_pb2'
  # @@protoc_insertion_point(class_scope:Realpayload)
  ))
_sym_db.RegisterMessage(Realpayload)


# @@protoc_insertion_point(module_scope)
