# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enums.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x65nums.proto*\xb9\x03\n\x05state\x12\x11\n\rAndhraPradesh\x10\x00\x12\x14\n\x10\x41runachalPradesh\x10\x01\x12\t\n\x05\x41ssam\x10\x02\x12\t\n\x05\x42ihar\x10\x03\x12\x10\n\x0c\x43hhattisgarh\x10\x04\x12\x07\n\x03Goa\x10\x05\x12\x0b\n\x07Gujarat\x10\x06\x12\x0b\n\x07Haryana\x10\x07\x12\x13\n\x0fHimachalPradesh\x10\x08\x12\x13\n\x0fJammuandKashmir\x10\t\x12\r\n\tJharkhand\x10\n\x12\r\n\tKarnataka\x10\x0b\x12\n\n\x06Kerala\x10\x0c\x12\x10\n\x0cMadyaPradesh\x10\r\x12\x0f\n\x0bMaharashtra\x10\x0e\x12\x0b\n\x07Manipur\x10\x0f\x12\r\n\tMeghalaya\x10\x10\x12\x0b\n\x07Mizoram\x10\x11\x12\x0c\n\x08Nagaland\x10\x12\x12\n\n\x06Orissa\x10\x13\x12\n\n\x06Punjab\x10\x14\x12\r\n\tRajasthan\x10\x15\x12\n\n\x06Sikkim\x10\x16\x12\r\n\tTamilNadu\x10\x17\x12\x0c\n\x08Telagana\x10\x18\x12\x0b\n\x07Tripura\x10\x19\x12\x0f\n\x0bUttaranchal\x10\x1a\x12\x10\n\x0cUttarPradesh\x10\x1b\x12\x0e\n\nWestBengal\x10\x1c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATE = _descriptor.EnumDescriptor(
  name='state',
  full_name='state',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AndhraPradesh', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ArunachalPradesh', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Assam', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Bihar', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Chhattisgarh', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Goa', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Gujarat', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Haryana', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HimachalPradesh', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JammuandKashmir', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jharkhand', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Karnataka', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Kerala', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MadyaPradesh', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Maharashtra', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Manipur', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Meghalaya', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mizoram', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Nagaland', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Orissa', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Punjab', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Rajasthan', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sikkim', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TamilNadu', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Telagana', index=24, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Tripura', index=25, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uttaranchal', index=26, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UttarPradesh', index=27, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WestBengal', index=28, number=28,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=16,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_STATE)

state = enum_type_wrapper.EnumTypeWrapper(_STATE)
AndhraPradesh = 0
ArunachalPradesh = 1
Assam = 2
Bihar = 3
Chhattisgarh = 4
Goa = 5
Gujarat = 6
Haryana = 7
HimachalPradesh = 8
JammuandKashmir = 9
Jharkhand = 10
Karnataka = 11
Kerala = 12
MadyaPradesh = 13
Maharashtra = 14
Manipur = 15
Meghalaya = 16
Mizoram = 17
Nagaland = 18
Orissa = 19
Punjab = 20
Rajasthan = 21
Sikkim = 22
TamilNadu = 23
Telagana = 24
Tripura = 25
Uttaranchal = 26
UttarPradesh = 27
WestBengal = 28


DESCRIPTOR.enum_types_by_name['state'] = _STATE


# @@protoc_insertion_point(module_scope)
