'use strict'; // code generated by pbf v3.2.1

var action = exports.action = {
    "register_farmer": {
        "value": 0,
        "options": {}
    },
    "register_buyer": {
        "value": 1,
        "options": {}
    },
    "register_transporter": {
        "value": 2,
        "options": {}
    },
    "otp_transaction": {
        "value": 3,
        "options": {}
    }
};

var state = exports.state = {
    "AndhraPradesh": {
        "value": 0,
        "options": {}
    },
    "ArunachalPradesh": {
        "value": 1,
        "options": {}
    },
    "Assam": {
        "value": 2,
        "options": {}
    },
    "Bihar": {
        "value": 3,
        "options": {}
    },
    "Chhattisgarh": {
        "value": 4,
        "options": {}
    },
    "Goa": {
        "value": 5,
        "options": {}
    },
    "Gujarat": {
        "value": 6,
        "options": {}
    },
    "Haryana": {
        "value": 7,
        "options": {}
    },
    "HimachalPradesh": {
        "value": 8,
        "options": {}
    },
    "JammuandKashmir": {
        "value": 9,
        "options": {}
    },
    "Jharkhand": {
        "value": 10,
        "options": {}
    },
    "Karnataka": {
        "value": 11,
        "options": {}
    },
    "Kerala": {
        "value": 12,
        "options": {}
    },
    "MadyaPradesh": {
        "value": 13,
        "options": {}
    },
    "Maharashtra": {
        "value": 14,
        "options": {}
    },
    "Manipur": {
        "value": 15,
        "options": {}
    },
    "Meghalaya": {
        "value": 16,
        "options": {}
    },
    "Mizoram": {
        "value": 17,
        "options": {}
    },
    "Nagaland": {
        "value": 18,
        "options": {}
    },
    "Orissa": {
        "value": 19,
        "options": {}
    },
    "Punjab": {
        "value": 20,
        "options": {}
    },
    "Rajasthan": {
        "value": 21,
        "options": {}
    },
    "Sikkim": {
        "value": 22,
        "options": {}
    },
    "TamilNadu": {
        "value": 23,
        "options": {}
    },
    "Telagana": {
        "value": 24,
        "options": {}
    },
    "Tripura": {
        "value": 25,
        "options": {}
    },
    "Uttaranchal": {
        "value": 26,
        "options": {}
    },
    "UttarPradesh": {
        "value": 27,
        "options": {}
    },
    "WestBengal": {
        "value": 28,
        "options": {}
    }
};

// Register_farmer ========================================

var Register_farmer = exports.Register_farmer = {};

Register_farmer.read = function (pbf, end) {
    return pbf.readFields(Register_farmer._readField, {aadhar_card: "", timestamp: 0, full_name: "", State: 0, pincode: 0, mobilenumber: 0, district: "", photo: null, otp: 0}, end);
};
Register_farmer._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.aadhar_card = pbf.readString();
    else if (tag === 2) obj.timestamp = pbf.readVarint();
    else if (tag === 3) obj.full_name = pbf.readString();
    else if (tag === 4) obj.State = pbf.readVarint();
    else if (tag === 5) obj.pincode = pbf.readVarint();
    else if (tag === 6) obj.mobilenumber = pbf.readVarint();
    else if (tag === 7) obj.district = pbf.readString();
    else if (tag === 8) obj.photo = pbf.readBytes();
    else if (tag === 9) obj.otp = pbf.readVarint();
};
Register_farmer.write = function (obj, pbf) {
    if (obj.aadhar_card) pbf.writeStringField(1, obj.aadhar_card);
    if (obj.timestamp) pbf.writeVarintField(2, obj.timestamp);
    if (obj.full_name) pbf.writeStringField(3, obj.full_name);
    if (obj.State) pbf.writeVarintField(4, obj.State);
    if (obj.pincode) pbf.writeVarintField(5, obj.pincode);
    if (obj.mobilenumber) pbf.writeVarintField(6, obj.mobilenumber);
    if (obj.district) pbf.writeStringField(7, obj.district);
    if (obj.photo) pbf.writeBytesField(8, obj.photo);
    if (obj.otp) pbf.writeVarintField(9, obj.otp);
};

// Register_buyer ========================================

var Register_buyer = exports.Register_buyer = {};

Register_buyer.read = function (pbf, end) {
    return pbf.readFields(Register_buyer._readField, {aadhar_card: "", timestamp: 0, full_name: "", State: 0, pincode: 0, mobilenumber: 0, district: "", photo: null, otp: 0}, end);
};
Register_buyer._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.aadhar_card = pbf.readString();
    else if (tag === 2) obj.timestamp = pbf.readVarint();
    else if (tag === 3) obj.full_name = pbf.readString();
    else if (tag === 4) obj.State = pbf.readVarint();
    else if (tag === 5) obj.pincode = pbf.readVarint();
    else if (tag === 6) obj.mobilenumber = pbf.readVarint();
    else if (tag === 7) obj.district = pbf.readString();
    else if (tag === 8) obj.photo = pbf.readBytes();
    else if (tag === 9) obj.otp = pbf.readVarint();
};
Register_buyer.write = function (obj, pbf) {
    if (obj.aadhar_card) pbf.writeStringField(1, obj.aadhar_card);
    if (obj.timestamp) pbf.writeVarintField(2, obj.timestamp);
    if (obj.full_name) pbf.writeStringField(3, obj.full_name);
    if (obj.State) pbf.writeVarintField(4, obj.State);
    if (obj.pincode) pbf.writeVarintField(5, obj.pincode);
    if (obj.mobilenumber) pbf.writeVarintField(6, obj.mobilenumber);
    if (obj.district) pbf.writeStringField(7, obj.district);
    if (obj.photo) pbf.writeBytesField(8, obj.photo);
    if (obj.otp) pbf.writeVarintField(9, obj.otp);
};

// Register_transporter ========================================

var Register_transporter = exports.Register_transporter = {};

Register_transporter.read = function (pbf, end) {
    return pbf.readFields(Register_transporter._readField, {aadhar_card: "", timestamp: 0, full_name: "", State: 0, pincode: 0, mobilenumber: 0, district: "", driving_license: "", photo: null, otp: 0}, end);
};
Register_transporter._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.aadhar_card = pbf.readString();
    else if (tag === 2) obj.timestamp = pbf.readVarint();
    else if (tag === 3) obj.full_name = pbf.readString();
    else if (tag === 4) obj.State = pbf.readVarint();
    else if (tag === 5) obj.pincode = pbf.readVarint();
    else if (tag === 6) obj.mobilenumber = pbf.readVarint();
    else if (tag === 7) obj.district = pbf.readString();
    else if (tag === 8) obj.driving_license = pbf.readString();
    else if (tag === 9) obj.photo = pbf.readBytes();
    else if (tag === 10) obj.otp = pbf.readVarint();
};
Register_transporter.write = function (obj, pbf) {
    if (obj.aadhar_card) pbf.writeStringField(1, obj.aadhar_card);
    if (obj.timestamp) pbf.writeVarintField(2, obj.timestamp);
    if (obj.full_name) pbf.writeStringField(3, obj.full_name);
    if (obj.State) pbf.writeVarintField(4, obj.State);
    if (obj.pincode) pbf.writeVarintField(5, obj.pincode);
    if (obj.mobilenumber) pbf.writeVarintField(6, obj.mobilenumber);
    if (obj.district) pbf.writeStringField(7, obj.district);
    if (obj.driving_license) pbf.writeStringField(8, obj.driving_license);
    if (obj.photo) pbf.writeBytesField(9, obj.photo);
    if (obj.otp) pbf.writeVarintField(10, obj.otp);
};

// Otp_transaction ========================================

var Otp_transaction = exports.Otp_transaction = {};

Otp_transaction.read = function (pbf, end) {
    return pbf.readFields(Otp_transaction._readField, {mobilenumber: 0, otp: 0, timestamp: 0}, end);
};
Otp_transaction._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.mobilenumber = pbf.readVarint();
    else if (tag === 2) obj.otp = pbf.readVarint();
    else if (tag === 3) obj.timestamp = pbf.readVarint();
};
Otp_transaction.write = function (obj, pbf) {
    if (obj.mobilenumber) pbf.writeVarintField(1, obj.mobilenumber);
    if (obj.otp) pbf.writeVarintField(2, obj.otp);
    if (obj.timestamp) pbf.writeVarintField(3, obj.timestamp);
};

// Realpayload ========================================

var Realpayload = exports.Realpayload = {};

Realpayload.read = function (pbf, end) {
    return pbf.readFields(Realpayload._readField, {Action: 0, reg_far: null, reg_buy: null, reg_tra: null, otp_tra: null}, end);
};
Realpayload._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.Action = pbf.readVarint();
    else if (tag === 2) obj.reg_far = Register_farmer.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 3) obj.reg_buy = Register_buyer.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.reg_tra = Register_transporter.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 5) obj.otp_tra = Otp_transaction.read(pbf, pbf.readVarint() + pbf.pos);
};
Realpayload.write = function (obj, pbf) {
    if (obj.Action) pbf.writeVarintField(1, obj.Action);
    if (obj.reg_far) pbf.writeMessage(2, Register_farmer.write, obj.reg_far);
    if (obj.reg_buy) pbf.writeMessage(3, Register_buyer.write, obj.reg_buy);
    if (obj.reg_tra) pbf.writeMessage(4, Register_transporter.write, obj.reg_tra);
    if (obj.otp_tra) pbf.writeMessage(5, Otp_transaction.write, obj.otp_tra);
};
